name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you implement this?
      placeholder: Describe the ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: Any alternative approaches you've thought about?
    validations:
      required: false
